#!/bin/ash

if [ ! -e /usr/local/sbin/system_stats_org ]; then
mv /usr/local/sbin/system_stats /usr/local/sbin/system_stats_org
cp /mnt/Anbernic/system_stats /usr/local/sbin/system_stats
else
cp /mnt/Anbernic/system_stats /usr/local/sbin/system_stats
fi

