#!/bin/ash

  if [ -d /mnt/FunKey ]; then
    rw
    cp /mnt/FunKey/snapshot_org /usr/local/sbin/snapshot
    ro
  elif [ -d /mnt/Anbernic ]; then
    cp /mnt/Anbernic/snapshot_org /usr/local/sbin/snapshot
  fi
