#!/bin/sh

# Uncomment the following line to get debug info
#set -x

# Check args
if [ ${#} -ne 0 ]; then
    echo "Usage: $(basename ${0})"
    exit 1
fi

# Lock file (necessary since fbgrab must run in bg not to block the buttons while gaming)
LOCK_FILE="/var/lock/snap.lock"
if [ -f "${LOCK_FILE}" ]; then
    echo "${LOCK_FILE} already exists"
    exit 1
fi
touch "${LOCK_FILE}"

# Increment name and save snapshot
SNAPSHOT_EXT=PNG
EXT=` ps -efHwww | grep opkrun| grep -v grep |awk -F. '{ print $NF }'`
SNAPSHOT_DIR=`ps -efH | grep opkrun| grep -v grep |awk -F/ '{ print "/"$5"/"$6 }'`
snapshot_file="`ps -efH | grep opkrun| grep -v grep |awk -F/ '{ print $NF }'|awk -F/ '{ print $NF }'|awk -F.${EXT} '{ print $1 }'`.png"
notif set 2 "   SCREENSHOT ${snapshot_file}"
fbgrab "${SNAPSHOT_DIR}/${snapshot_file}" >/dev/null 2>&1 &

# Remove lock file
rm -f "${LOCK_FILE}"

exit 0
